[project]
name = "solar-hydrogen-dashboard"
version = "1.0.0"
description = "Dashboard Solar para Proyecto de Hidrógeno"
requires-python = ">=3.13,<3.14"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
